### ISSUE TITLE
DateTime representation

### ISSUE THREAD

**Issue by simplogical** [gimmi/extdirecthandler#12]
I have a WCF servcice that returns a DateTime field. When I use this in a Ext.grid.Panel as a datacolumn, the data is incorrectly interpreted. If displayed as a simple gridcolumn, the value looks like: /Date(1331757784000-0400)/.

**Comment by gimmi** [comment]
Sorry I don't understand: are you using ExtDirectHandler or WCF?

**Comment by simplogical** [comment]
Sorry - that wasn't a very clear description. I am using ExtDirectHandler - the C# handler itself happens to be talking to a backend via WCF, but that's immaterial.

I can write a simple C# handler and pass a DateTime in the response, and the JS application cannot interpret it correctly.

**Comment by gimmi** [comment]
You can customize how JSON.NET serialize objects to JSON and back. I-ve added a wiki page that describe how this can be done:

https://github.com/gimmi/extdirecthandler/wiki/Customize-JSON-serialization

For more info on JSON.NET configuration please refer to JSON.NET documentation located at:

http://james.newtonking.com/projects/json/help/

For your specific case, using IsoDateTimeConverter should be enough.

Hope this helps!

**Comment by simplogical** [comment]
Somewhat - it appears that I now get back a formated text field - kind of an improvement, but now I can't treat it as a date on the ExtJs side. I need to do a bit more research now with the info you've given me. I'll update when I get to a conclusion.

Thanks again for your time and for getting to this quickly!

**Comment by simplogical** [comment]
I had to do a little more work (snippet included) to coerce the date format into something that ExtJS recognizes - it doesn't seem to like the default ISO format. The following worked for me:

```
    private static JsonSerializer BuildJsonSerializer()
    {
        var ret = new JsonSerializer
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver()
        };
        var dtc = new IsoDateTimeConverter();
        dtc.DateTimeFormat = "yyyy'/'MM'/'dd' 'HH':'mm':'ss";
        ret.Converters.Add(dtc);
        return ret;
    }
```
