### ISSUE TITLE
Ext.app.REMOTING_API is undefined

### ISSUE THREAD

**Issue by harinpatel** [gimmi/extdirecthandler#5]
When run project from visual studio in debug mode it works  fine.
But after deploying it in IIS on other machine it doesnt work. so i debug the line when
we add provider and i found Ext.app.REMOTING_API was undefined.

Ext.onReady(function () {
    // Add Ext Direct for .NET
    Ext.Direct.addProvider(Ext.app.REMOTING_API);

Any idea? was there any setting in IIS needed to make ext direct remoting work?

**Comment by gimmi** [comment]
If you are on IIS7+ try to move the following code in your web.config:

&lt;system.web&gt;
    &lt;httpHandlers&gt;
      &lt;add verb=&quot;*&quot; path=&quot;rpc&quot; type=&quot;ExtDirectHandler.DirectHttpHandler, ExtDirectHandler&quot; /&gt;
    &lt;/httpHandlers&gt;
&lt;/system.web&gt;

To

&lt;system.webServer&gt;
    &lt;handlers&gt;
      &lt;add name=&quot;ExtDirectHandler.DirectHttpHandler&quot; verb=&quot;*&quot; path=&quot;rpc&quot; type=&quot;ExtDirectHandler.DirectHttpHandler, ExtDirectHandler&quot;/&gt;
    &lt;/handlers&gt;
&lt;/system.webServer&gt;

**Comment by harinpatel** [comment]
thanks for response gimmi.

But i am using IIS6.0. so i have still issue...

**Comment by gimmi** [comment]
Try to add ".ashx" extension to the handler path, for example:

&lt;add verb=&quot;*&quot; path=&quot;rpc.ashx&quot; type=&quot;ExtDirectHandler.DirectHttpHandler, ExtDirectHandler&quot; /&gt;

**Comment by harinpatel** [comment]
it works. the issue was asp.net version which has to be set from IIS to 4.0.
i was setting 4.0 in web.config which seems to not working.
Again thanks a lot for all your help.

**Comment by harinpatel** [comment]
I could set it on one machine on IIS6.0.
but on other machine same issue occurs eventhough it is hosted on ASP 4.0 and IIS 6.0.
one difference i found is that on other machine there is no Rpc / RpcWithCCert folder under Default Web Site.  
While in the machine it works it has those folders(which are pointing to Rpc).i reaserched little bit about rpc support 
for http but it more seems for exchange server. 
Since this ext direct stack use rpc handler do we have to enable anything for RpcProxy for IIS? 

Any help will be appreciated in advance.

**Comment by gimmi** [comment]
ExtDirectHandler has nothing to do with RpcWithCCert/RpcProxy.
ExtDirectHandler is just an HttpHandler that can exposed whith the name you prefer, in the example code in the wiki is exposed with the "rpc" name, but you can change it.

`<add verb="*" path="PUT HERE THE NAME YOU PREFER" type="ExtDirectHandler.DirectHttpHandler, ExtDirectHandler" />`

Try to change name and see if it works. Another good idea is to name it using ".ashx" extension, so:

`<add verb="*" path="rpc.ashx" type="ExtDirectHandler.DirectHttpHandler, ExtDirectHandler" />`

**Comment by harinpatel** [comment]
this error is fixed by proper deployment and setting .net 4.0 on IIS 6.0
