### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by DavidSSL** [gimmi/extdirecthandler#6]
Hi,

I wanted to get a copy of your code, compile and run the sample web application. However, I've obtained the code both using the zipped file facility and getting the source code via github. However, when I try to compile, "SharedAssemblyInfo.cs" causes problems and I'm told that the file cannot be found. Can you please advise?

Regards,

David

**Comment by gimmi** [comment]
When you first clone the repository, run the following commandline from the root directory of the repository:

build.cmd assemblyinfo
